package game.vt.silence.game_mech.model;

import java.util.Arrays;

public enum VTValue {
    VALUE_EXPERIENCE_MAX(VTValueTag.EXPERIENCE),
    VALUE_EXPERIENCE_ACTUAL(VTValueTag.EXPERIENCE),
    VALUE_TICKS(),
    TALENT_LIMIT(),

    VITAL_STATS_HEALTH_MAX(VTValueTag.VITAL_STATE, VTValueTag.HEALTH),
    VITAL_STATS_HEALTH_ACTUAL(VTValueTag.VITAL_STATE, VTValueTag.HEALTH),
    VITAL_STATS_HEALTH_ADD(VTValueTag.VITAL_STATE, VTValueTag.HEALTH),
    VITAL_STATS_HEALTH_CRISIS(VTValueTag.VITAL_STATE, VTValueTag.HEALTH),

    BLOCK_ENDURANCE(VTValueTag.BLOCK),
    SKILL_ENDURANCE_PHYSIQUE(VTValueTag.SKILL, VTValueTag.ENDURANCE),
    SKILL_ENDURANCE_HAND_TO_HAND_COMBAT(VTValueTag.SKILL, VTValueTag.ENDURANCE),
    SKILL_ENDURANCE_HEAVY_WEAPONS(VTValueTag.SKILL, VTValueTag.ENDURANCE),
    SKILL_ENDURANCE_ADAPTABILITY(VTValueTag.SKILL, VTValueTag.ENDURANCE),
    SKILL_ENDURANCE_SENSE_OF_TOWN(VTValueTag.SKILL, VTValueTag.ENDURANCE),
    SKILL_ENDURANCE_MUTATION(VTValueTag.SKILL, VTValueTag.ENDURANCE, VTValueTag.SPECIAL_SKILL),

    BLOCK_SWIFTNESS(VTValueTag.BLOCK),
    SKILL_SWIFTNESS_PRECISION(VTValueTag.SKILL, VTValueTag.SWIFTNESS),
    SKILL_SWIFTNESS_MOBILITY(VTValueTag.SKILL, VTValueTag.SWIFTNESS),
    SKILL_SWIFTNESS_STEALTH(VTValueTag.SKILL, VTValueTag.SWIFTNESS),
    SKILL_SWIFTNESS_FENCING(VTValueTag.SKILL, VTValueTag.SWIFTNESS),
    SKILL_SWIFTNESS_ACCURACY(VTValueTag.SKILL, VTValueTag.SWIFTNESS),
    SKILL_SWIFTNESS_SLITHERING(VTValueTag.SKILL, VTValueTag.SWIFTNESS, VTValueTag.SPECIAL_SKILL),

    VITAL_STATS_SANITY_MAX(VTValueTag.VITAL_STATE, VTValueTag.SANITY),
    VITAL_STATS_SANITY_ACTUAL(VTValueTag.VITAL_STATE, VTValueTag.SANITY),
    VITAL_STATS_SANITY_ADD(VTValueTag.VITAL_STATE, VTValueTag.SANITY),
    VITAL_STATS_SANITY_CRISIS(VTValueTag.VITAL_STATE, VTValueTag.SANITY),

    BLOCK_MIND(VTValueTag.BLOCK),
    SKILL_MIND_SEARCH(VTValueTag.SPECIAL_SKILL, VTValueTag.MIND),
    SKILL_MIND_PLANNING(VTValueTag.SPECIAL_SKILL, VTValueTag.MIND),
    SKILL_MIND_MECHANICS(VTValueTag.SPECIAL_SKILL, VTValueTag.MIND),
    SKILL_MIND_MEDICINE(VTValueTag.SPECIAL_SKILL, VTValueTag.MIND),
    SKILL_MIND_CHEMISTRY(VTValueTag.SPECIAL_SKILL, VTValueTag.MIND),
    SKILL_MIND_AUTOIMMERSION(VTValueTag.SPECIAL_SKILL, VTValueTag.MIND, VTValueTag.SPECIAL_SKILL),

    BLOCK_EGO(VTValueTag.BLOCK),
    SKILL_EGO_MANIPULATION(VTValueTag.SKILL, VTValueTag.EGO),
    SKILL_EGO_PSYCHOANALYSIS(VTValueTag.SKILL, VTValueTag.EGO),
    SKILL_EGO_CREATIVITY(VTValueTag.SKILL, VTValueTag.EGO),
    SKILL_EGO_SELF_CONTROL(VTValueTag.SKILL, VTValueTag.EGO),
    SKILL_EGO_HYPNOSIS(VTValueTag.SKILL, VTValueTag.EGO),
    SKILL_EGO_WILLPOWER(VTValueTag.SKILL, VTValueTag.EGO, VTValueTag.SPECIAL_SKILL),

    CONNECTIONS_ACADEMIES(VTValueTag.CONNECTIONS),
    CONNECTIONS_AUTHORITIES(VTValueTag.CONNECTIONS),
    CONNECTIONS_ARISTOCRACY(VTValueTag.CONNECTIONS),
    CONNECTIONS_BUSINESS(VTValueTag.CONNECTIONS),
    CONNECTIONS_ART(VTValueTag.CONNECTIONS),
    CONNECTIONS_ARMY(VTValueTag.CONNECTIONS),
    CONNECTIONS_CRIMINALS(VTValueTag.CONNECTIONS),
    CONNECTIONS_OCCULT(VTValueTag.CONNECTIONS),
    CONNECTIONS_INFRASTRUCTURE(VTValueTag.CONNECTIONS),
    CONNECTIONS_STEPPE(VTValueTag.CONNECTIONS),

    KNOWLEDGE_ACADEMIES(VTValueTag.KNOWLEDGE),
    KNOWLEDGE_AUTHORITIES(VTValueTag.KNOWLEDGE),
    KNOWLEDGE_ARISTOCRACY(VTValueTag.KNOWLEDGE),
    KNOWLEDGE_BUSINESS(VTValueTag.KNOWLEDGE),
    KNOWLEDGE_ART(VTValueTag.KNOWLEDGE),
    KNOWLEDGE_ARMY(VTValueTag.KNOWLEDGE),
    KNOWLEDGE_CRIMINALS(VTValueTag.KNOWLEDGE),
    KNOWLEDGE_OCCULT(VTValueTag.KNOWLEDGE),
    KNOWLEDGE_INFRASTRUCTURE(VTValueTag.KNOWLEDGE),
    KNOWLEDGE_STEPPE(VTValueTag.KNOWLEDGE),

    CAP_DRIVE(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_STRESS(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_PLAN(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_ILLNESS(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_SWIFTNESS_CONDITION(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_INSPIRATION(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_INTOXICATION(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_REGENERATION(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_PASSION(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_LIGHT(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_GREYNESS(VTValueTag.CONDITIONS_AND_PROCESSES),
    CAP_DARKNESS(VTValueTag.CONDITIONS_AND_PROCESSES);

    private VTValueTag[] tags;

    VTValue(VTValueTag... tags) {
        this.tags = tags;

    }

    /*public List<VTValueTag> getTags() {
        return tags;
    }*/

    public boolean containsTag(VTValueTag tag) {
        return Arrays.stream(tags).anyMatch(x -> x == tag);
    }
}
